# Generated by Django 4.2.30 on 2026-05-28 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='phone_ext',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='team',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(blank=True, help_text='Display/call center name', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='five9_password',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agent',
            name='five9_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='scheduling.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='teams_password',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
