# Generated by Django 4.2.30 on 2026-05-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_agent_phone_ext_remove_agent_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('testing', 'Testing'), ('sms_email', 'SMS/Email'), ('admin_training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin')], default='agent', max_length=20),
        ),
    ]
