# Generated by Django 4.2.30 on 2026-05-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_agent_role_type_alter_agent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('testing', 'Testing'), ('sms_email', 'SMS/Email'), ('admin_training', 'Training'), ('coordinator', 'Coordinator')], max_length=20),
        ),
    ]
