# Generated by Django 4.2.30 on 2026-05-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_agent_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
