# Generated by Django 4.2.30 on 2026-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
