# Generated by Django 4.2.30 on 2026-05-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_agent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
