# Generated by Django 4.2.30 on 2026-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_agent_termination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone_country_code',
            field=models.CharField(blank=True, choices=[('+1', '+1 (US/Canada)'), ('+52', '+52 (Mexico)')], default='+1', max_length=5),
        ),
    ]
