# Generated by Django 4.2.30 on 2026-05-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_agent_phone_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason_ended', models.CharField(blank=True, choices=[('', '— Active / No reason —'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('laid_off', 'Laid Off'), ('contract_end', 'Contract Ended'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_periods', to='scheduling.agent')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
