# Generated by Django 4.2.30 on 2026-05-28 17:56

from django.db import migrations


def seed_periods(apps, schema_editor):
    Agent = apps.get_model('scheduling', 'Agent')
    EmploymentPeriod = apps.get_model('scheduling', 'EmploymentPeriod')
    for agent in Agent.objects.all():
        if agent.start_date and not EmploymentPeriod.objects.filter(agent=agent).exists():
            EmploymentPeriod.objects.create(
                agent=agent,
                start_date=agent.start_date,
                end_date=agent.termination_date,
                reason_ended='terminated' if agent.termination_date else '',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_employment_period'),
    ]

    operations = [
        migrations.RunPython(seed_periods, migrations.RunPython.noop),
    ]
