# Generated by Django 4.2.30 on 2026-05-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_seed_employment_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Five9Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. Primary, Kill Team, Overtime', max_length=100)),
                ('five9_username', models.CharField(max_length=150)),
                ('five9_password', models.CharField(blank=True, max_length=150)),
                ('role_type', models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('testing', 'Testing'), ('sms_email', 'SMS/Email'), ('admin_training', 'Training'), ('coordinator', 'Coordinator')], max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five9_profiles', to='scheduling.agent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
