# Generated by Django 4.2.30 on 2026-06-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_agent_employer_billing_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='overtimeshift',
            name='base_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='overtimeshift',
            name='incentive_type',
            field=models.CharField(choices=[('none', 'No Incentive'), ('time_and_a_half', 'Time & a Half (1.5x)'), ('power_hour', 'Power Hour (2x)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='overtimeshift',
            name='incentivized_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='overtimeshift',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
