# Generated by Django 4.2.30 on 2026-06-02 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_ot_incentive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimeshift',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ShiftTemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_blocks', to='scheduling.shifttemplate')),
            ],
            options={
                'ordering': ['block_number'],
                'unique_together': {('shift_template', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='ShiftBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_blocks', to='scheduling.shift')),
            ],
            options={
                'ordering': ['block_number'],
                'unique_together': {('shift', 'block_number')},
            },
        ),
    ]
