# Generated by Django 4.2.30 on 2026-06-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_split_shifts_multi_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
