# Generated by Django 4.2.30 on 2026-06-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_shifttemplate_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='effective_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
