# Generated by Django 4.2.30 on 2026-06-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_shifttemplate_effective_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttemplate',
            options={'ordering': ['day_of_week', 'effective_from']},
        ),
        migrations.AlterUniqueTogether(
            name='shifttemplate',
            unique_together=set(),
        ),
    ]
