# Generated by Django 4.2.30 on 2026-06-04 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_overtimeshift_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogoutUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OTShiftVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_seconds', models.IntegerField(default=0)),
                ('shift_seconds', models.IntegerField(default=0)),
                ('username_found', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('ot_shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='scheduling.overtimeshift')),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='scheduling.loginlogoutupload')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five9_username', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('login_at', models.DateTimeField()),
                ('logout_at', models.DateTimeField()),
                ('session_seconds', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_sessions', to='scheduling.agent')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.loginlogoutupload')),
            ],
            options={
                'ordering': ['date', 'login_at'],
                'indexes': [models.Index(fields=['agent', 'date'], name='scheduling__agent_i_2deb64_idx'), models.Index(fields=['five9_username', 'date'], name='scheduling__five9_u_743d8c_idx')],
            },
        ),
    ]
