# Generated by Django 4.2.30 on 2026-06-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0028_scheduledrolechange_new_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('coding', 'Coding Request'), ('vacation', 'Vacation Request'), ('day_off_change', 'Day Off Change Request'), ('vto', 'VTO Request'), ('loa', 'LOA Request'), ('schedule_change', 'Schedule Change Request')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('done', 'Done')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('coding_date', models.DateField(blank=True, null=True)),
                ('coding_start_time', models.TimeField(blank=True, null=True)),
                ('coding_end_time', models.TimeField(blank=True, null=True)),
                ('vacation_start', models.DateField(blank=True, null=True)),
                ('vacation_end', models.DateField(blank=True, null=True)),
                ('day_off_type', models.CharField(blank=True, max_length=10)),
                ('current_day_off', models.IntegerField(blank=True, null=True)),
                ('requested_day_off', models.IntegerField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('vto_date', models.DateField(blank=True, null=True)),
                ('loa_start', models.DateField(blank=True, null=True)),
                ('loa_end', models.DateField(blank=True, null=True)),
                ('current_schedule_desc', models.TextField(blank=True)),
                ('requested_schedule_desc', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('auto_action_log', models.TextField(blank=True)),
                ('supervisor_read', models.BooleanField(default=False)),
                ('agent_read', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requests', to='scheduling.agent')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_agent_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
