# Generated by Django 4.2.30 on 2026-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0029_agentrequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='overtimeshift',
            index=models.Index(fields=['agent', 'date'], name='scheduling__agent_i_6a9790_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeshift',
            index=models.Index(fields=['date'], name='scheduling__date_535de3_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['agent', 'date'], name='scheduling__agent_i_e4fca4_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date'], name='scheduling__date_51788f_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['agent', 'day_of_week'], name='scheduling__agent_i_2eea27_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['agent', 'day_of_week', 'effective_from'], name='scheduling__agent_i_d14fc7_idx'),
        ),
    ]
