# Generated by Django 4.2.30 on 2026-06-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='schedule_change_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='schedule_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='schedule_new_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='schedule_new_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
