# Generated by Django 4.2.30 on 2026-06-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0031_agentrequest_schedule_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSeparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_type', models.CharField(choices=[('quit', 'Quit (Voluntary)'), ('terminated', 'Terminated (Involuntary)'), ('abandonment', 'Job Abandonment'), ('contract_end', 'End of Contract'), ('resigned_notice', 'Resigned with Notice')], max_length=20)),
                ('last_day_worked', models.DateField()),
                ('separation_date', models.DateField(help_text='First day agent no longer appears on Adherence')),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='separation', to='scheduling.agent')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separations_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
