# Generated by Django 4.2.30 on 2026-06-23 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0034_five9profile_billable_primary_agent_billing_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('62.50'), help_text='Agent pay rate in MXN', max_digits=8, null=True),
        ),
    ]
