# Generated by Django 4.2.30 on 2026-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0036_backfill_agent_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='admin_bonus_mxn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual admin bonus in MXN (uses global default if blank)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_official_admin',
            field=models.BooleanField(default=False, help_text='Genuine administrator — receives admin bonus instead of adherence bonus'),
        ),
    ]
