# Generated by Django 4.2.30 on 2026-06-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0039_set_super_admin_david'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('testing', 'Testing'), ('sms_email', 'SMS/Email'), ('coordinator', 'Coordinator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='five9profile',
            name='role_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('testing', 'Testing'), ('sms_email', 'SMS/Email'), ('coordinator', 'Coordinator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledrolechange',
            name='new_role_type',
            field=models.CharField(choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('testing', 'Testing'), ('sms_email', 'SMS/Email'), ('coordinator', 'Coordinator')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Break',
        ),
    ]
