# Generated by Django 4.2.30 on 2026-06-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0040_remove_break_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='five9profile',
            index=models.Index(fields=['agent', 'billable'], name='scheduling__agent_i_bf6e8d_idx'),
        ),
    ]
