# Generated by Django 4.2.30 on 2026-07-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0042_rename_testing_to_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff_requests', to='scheduling.agent'),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='is_staff_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('tester', 'Tester'), ('sms_email', 'SMS/Email'), ('coordinator', 'Coordinator'), ('trainer', 'Trainer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='five9profile',
            name='role_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('tester', 'Tester'), ('sms_email', 'SMS/Email'), ('coordinator', 'Coordinator'), ('trainer', 'Trainer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledrolechange',
            name='new_role_type',
            field=models.CharField(choices=[('training', 'Training'), ('incubation', 'Incubation'), ('regular_agent', 'Regular Agent'), ('kill_team', 'Kill Team'), ('night_shift', 'Night Shift'), ('supervisor', 'Supervisor'), ('qa', 'QA'), ('cs', 'CS'), ('tester', 'Tester'), ('sms_email', 'SMS/Email'), ('coordinator', 'Coordinator'), ('trainer', 'Trainer')], max_length=20),
        ),
    ]
