# Generated by Django 4.2.30 on 2026-07-07 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0043_agentrequest_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenOTShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('incentive_type', models.CharField(choices=[('none', 'No Incentive'), ('time_and_a_half', 'Time & a Half (1.5x)'), ('power_hour', 'Power Hour (2x)')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled')], default='open', max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_posting', to='scheduling.overtimeshift')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_open_ot_shifts', to='scheduling.agent')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_open_ot_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='OTShiftClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('supervisor_read', models.BooleanField(default=False)),
                ('requester_read', models.BooleanField(default=True)),
                ('open_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='scheduling.openotshift')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_claim_requests', to='scheduling.agent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ot_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OTCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('supervisor_read', models.BooleanField(default=False)),
                ('requester_read', models.BooleanField(default=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_cancellation_requests', to='scheduling.agent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ot_cancellations', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='scheduling.overtimeshift')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='openotshift',
            index=models.Index(fields=['status', 'date'], name='scheduling__status_1a6798_idx'),
        ),
    ]
