# Generated by Django 4.2.30 on 2026-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0044_openotshift_otshiftclaimrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openotshift',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('removed', 'Removed')], default='open', max_length=10),
        ),
    ]
