# Generated by Django 4.2.30 on 2026-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0045_alter_openotshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_access_admin_tabs',
            field=models.BooleanField(default=False, help_text='Access to Admin Codings and Admin Adherence — supervisors see & code their own team of Official Admins; super admins see everyone'),
        ),
    ]
