# Generated by Django 4.2.30 on 2026-08-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0045_alter_openotshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_access_admin_attendance',
            field=models.BooleanField(default=False, help_text="Access to Admin Attendance — supervisors see and edit their own team's attendance; super admins see everyone"),
        ),
    ]
