# Generated by Django 4.2.30 on 2026-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0046_agent_can_access_admin_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_manage_loans',
            field=models.BooleanField(default=False, help_text='Access to the Nómina Loans module — add loans and mark repayments; super admins always have access'),
        ),
    ]
