# Generated by Django 4.2.30 on 2026-08-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0048_set_default_admin_attendance_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adherence_start_date',
            field=models.DateField(blank=True, help_text='First Monday this agent should appear on the Adherence tab. Leave blank for no change — this is opt-in only.', null=True),
        ),
    ]
