# Generated by Django 4.2.30 on 2026-08-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0049_agent_adherence_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='can_auto_code_requests',
            field=models.BooleanField(default=False, help_text="Approving this agent's coding request automatically creates the coding — bypasses manual entry on the Codings tab"),
        ),
    ]
