# Generated by Django 4.2.30 on 2026-08-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0049_agent_adherence_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adherence_bonus_max_mxn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual adherence-bonus cap in MXN (uses global default if blank); proration rule is unchanged', max_digits=8, null=True),
        ),
    ]
