# Generated by Django 4.2.30 on 2026-08-25 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0052_set_erick_adherence_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_agent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
