# Generated by Django 4.2.30 on 2026-09-26 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_primary_periods(apps, schema_editor):
    """Give every agent who has a primary account today one 'from the beginning'
    entry for it, so the date-aware resolver returns exactly the same answer as
    the is_primary flag did, for every agent and every date.

    Writes rows only: no display-hours recalculation and no Activity Log entries,
    because nothing anyone can observe changes.

    An agent with no primary account gets nothing and keeps resolving to nobody,
    exactly as before.

    One stated behavior change, in one shape only: an agent with TWO OR MORE
    accounts marked primary used to have BOTH counted, which a single entry
    cannot express. The lowest-id one is seeded and is_primary is cleared on the
    others, so the flag and the history agree from the first moment.
    five9_account_setup_report's first production run (2026-09-25) found 0 agents
    in its 'more than one account marked primary' section.
    """
    Five9Profile = apps.get_model('scheduling', 'Five9Profile')
    Five9PrimaryPeriod = apps.get_model('scheduling', 'Five9PrimaryPeriod')

    winners = {}          # agent_id -> the profile that stays primary
    extra_pks = []        # duplicates to un-mark
    for p in Five9Profile.objects.filter(is_primary=True).order_by('id'):
        if p.agent_id in winners:
            extra_pks.append(p.pk)
        else:
            winners[p.agent_id] = p

    Five9PrimaryPeriod.objects.bulk_create([
        Five9PrimaryPeriod(
            agent_id=agent_id,
            profile=profile,
            five9_username=profile.five9_username,
            start_date=None,
            end_date=None,
            kind='initial',
            created_by=None,
        )
        for agent_id, profile in sorted(winners.items())
    ])

    if extra_pks:
        Five9Profile.objects.filter(pk__in=extra_pks).update(is_primary=False)


def unseed_primary_periods(apps, schema_editor):
    """Reverse leaves is_primary untouched — it is already the flag the seed read."""
    apps.get_model('scheduling', 'Five9PrimaryPeriod').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0054_skill_skillrenamehistory_agentskillchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Five9PrimaryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five9_username', models.CharField(help_text='Snapshot of the username; used only once the account itself is gone', max_length=150)),
                ('start_date', models.DateField(blank=True, help_text='Blank means from the beginning', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Blank means open-ended', null=True)),
                ('kind', models.CharField(choices=[('initial', 'From the beginning'), ('switch', 'Switched'), ('always', 'Always the primary'), ('past_period', 'Past period')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five9_primary_periods', to='scheduling.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_periods', to='scheduling.five9profile')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['agent'], name='scheduling__agent_i_a17d8d_idx')],
            },
        ),
        migrations.RunPython(seed_primary_periods, unseed_primary_periods),
    ]
