from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('agents/', views.agent_list, name='agent_list'),
    path('agents/add/', views.agent_create, name='agent_create'),
    path('agents/<int:pk>/', views.agent_detail, name='agent_detail'),
    path('agents/<int:pk>/edit/', views.agent_edit, name='agent_edit'),
    path('agents/<int:pk>/delete/', views.agent_delete, name='agent_delete'),
    path('shifts/', views.shift_list, name='shift_list'),
    path('shifts/week/', views.shift_week, name='shift_week'),
    path('shifts/copy-from-prev/', views.shift_copy_from_prev, name='shift_copy_from_prev'),
    path('shifts/copy-agent-from-prev/', views.shift_copy_agent_from_prev, name='shift_copy_agent_from_prev'),
    path('shifts/<int:pk>/edit/', views.shift_edit, name='shift_edit'),
    path('shifts/<int:pk>/delete/', views.shift_delete, name='shift_delete'),
    path('shifts/clear-recurring/', views.shift_clear_recurring, name='shift_clear_recurring'),
    path('overtime/', views.overtime_list, name='overtime_list'),
    path('overtime/week/', views.overtime_week, name='overtime_week'),
    path('overtime/export/', views.overtime_export, name='overtime_export'),
    path('overtime/<int:pk>/delete/', views.overtime_delete, name='overtime_delete'),
    path('overtime/<int:pk>/set-status/', views.overtime_set_status, name='overtime_set_status'),
    path('shifts/quick-edit/', views.shift_quick_edit, name='shift_quick_edit'),
    path('activity/', views.activity_log, name='activity_log'),
    path('poll/', views.live_poll, name='live_poll'),
    path('agents/<int:pk>/history/', views.agent_history, name='agent_history'),
    path('records/', views.records_attendance, name='records_attendance'),
    path('records/hours/', views.records_hours, name='records_hours'),
    path('records/roles/', views.records_role_log, name='records_role_log'),
]
