# Generated by Django 4.2.30 on 2026-06-23 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsettings',
            name='billing_rate_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Infinity billing rate to LCC (USD per hour, applies to all billable employees)', max_digits=8),
        ),
    ]
