# Generated by Django 4.2.30 on 2026-06-23 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_backfill_billing_rate_15'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsettings',
            name='adherence_bonus_mxn',
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='adherence_bonus_full_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Hours threshold for full bonus — agents below this receive a proportional amount', max_digits=5),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='adherence_bonus_max_mxn',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), help_text='Maximum adherence bonus in MXN (paid in full when hours >= threshold)', max_digits=8),
        ),
    ]
