# Generated by Django 4.2.30 on 2026-06-23 17:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_adherence_bonus_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='default_admin_bonus_mxn',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Default admin bonus in MXN for Official Admins (overridable per-profile)', max_digits=8),
        ),
    ]
