# Generated by Django 4.2.30 on 2026-06-24 00:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_billing_settings_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='default_tardy_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Hours assumed lost for a Tardy day when no actual login was recorded (default 0.25 = 15 min)', max_digits=4),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='nr_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1250'), help_text='NR allowance as a fraction of login+codings time (default 0.125 = 12.5%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='nr_ratio_max_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('48.00'), help_text='NR ratio deduction only applies when weekly pre-NR hours ≤ this value (default 48)', max_digits=5),
        ),
        migrations.AddField(
            model_name='billingsettingshistory',
            name='default_tardy_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4),
        ),
        migrations.AddField(
            model_name='billingsettingshistory',
            name='nr_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1250'), max_digits=6),
        ),
        migrations.AddField(
            model_name='billingsettingshistory',
            name='nr_ratio_max_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('48.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='billingsettingshistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
