# Generated by Django 4.2.30 on 2026-08-05 05:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_nr_ratio_and_tardy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsettings',
            name='nr_ratio_max_hours',
        ),
        migrations.RemoveField(
            model_name='billingsettingshistory',
            name='nr_ratio_max_hours',
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='nr_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1250'), help_text='NR allowance as a fraction of connected (login + coded) time (default 0.125 = 12.5%), capped at the weekly NR cap', max_digits=6),
        ),
    ]
