# Generated by Django 4.2.30 on 2026-08-03 04:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0046_agent_can_access_admin_tabs'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('spiff_fx_rate', models.DecimalField(decimal_places=4, default=Decimal('17.41'), help_text='USD→MXN rate used to convert spiffs this week', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPayInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('lpo', models.DecimalField(decimal_places=2, default=0, help_text='Sales commission (MXN)', max_digits=10)),
                ('spiff_usd', models.DecimalField(decimal_places=2, default=0, help_text="Spiffs in USD (converted at the week's rate)", max_digits=10)),
                ('welcome', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kill_team_qa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comedor', models.DecimalField(decimal_places=2, default=0, help_text='Cafeteria charges — deducted', max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, help_text='Transportation — deducted', max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_inputs', to='scheduling.agent')),
            ],
            options={
                'unique_together': {('agent', 'week_start')},
            },
        ),
    ]
