# Generated by Django 4.2.30 on 2026-08-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0046_agent_can_access_admin_tabs'),
        ('nomina', '0002_nominaweek_weeklypayinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakAbuseIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_abuse_incidents', to='scheduling.agent')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
