# Generated by Django 4.2.30 on 2026-08-03 05:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0046_agent_can_access_admin_tabs'),
        ('nomina', '0003_breakabuseincident'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeBonusEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10)),
                ('num_weeks', models.PositiveSmallIntegerField(default=4)),
                ('start_week', models.DateField(help_text='Monday of the first eligible week')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_welcome', to='scheduling.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term_weeks', models.PositiveSmallIntegerField(choices=[(1, '1 week (×1.25)'), (2, '2 weeks (×1.35)')], default=1)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=5)),
                ('start_week', models.DateField(help_text='Monday of the first repayment week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_loans', to='scheduling.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NominaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('field', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_overrides', to='scheduling.agent')),
            ],
            options={
                'unique_together': {('agent', 'week_start', 'field')},
            },
        ),
    ]
