# Generated by Django 4.2.30 on 2026-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_welcomebonusenrollment_loan_nominaoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominaweek',
            name='spiff_fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD→MXN rate for spiffs — set each week (starts empty)', max_digits=8, null=True),
        ),
    ]
