# Generated by Django 4.2.30 on 2026-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_alter_nominaweek_spiff_fx_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedInputRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('input_key', models.CharField(max_length=20)),
                ('who', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['who'],
                'indexes': [models.Index(fields=['week_start', 'input_key', 'acknowledged'], name='nomina_unma_week_st_641d29_idx')],
            },
        ),
    ]
