# Generated by Django 4.2.30 on 2026-08-03 21:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_agent_can_manage_loans'),
        ('nomina', '0006_unmatchedinputrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_adjustments', to='scheduling.agent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.agent')),
            ],
            options={
                'unique_together': {('agent', 'year')},
            },
        ),
    ]
