# Generated by Django 4.2.30 on 2026-08-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_agent_can_manage_loans'),
        ('nomina', '0007_vacationadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='The loan manager who handed this out — credited the amount back on their Admin Nómina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_granted', to='scheduling.agent'),
        ),
    ]
