# Generated by Django 4.2.30 on 2026-08-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_loan_granted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayinput',
            name='extra_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual hours correction — folds into Hours Worked + Pay (48)', max_digits=7),
        ),
    ]
