# Generated by Django 4.2.30 on 2026-08-04 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_agent_can_manage_loans'),
        ('nomina', '0009_weeklypayinput_extra_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBonusDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('deduction_pct', models.DecimalField(decimal_places=2, default=0, help_text='0–100', max_digits=5)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bonus_deductions', to='scheduling.agent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.agent')),
            ],
            options={
                'unique_together': {('agent', 'week_start')},
            },
        ),
    ]
