# Generated by Django 4.2.30 on 2026-08-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_agent_can_manage_loans'),
        ('nomina', '0010_adminbonusdeduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('agent_rows', models.JSONField(default=list)),
                ('agent_yours_rows', models.JSONField(default=list)),
                ('agent_totals', models.JSONField(default=dict)),
                ('admin_rows', models.JSONField(default=list)),
                ('admin_totals', models.JSONField(default=dict)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.agent')),
            ],
        ),
    ]
