# Generated by Django 4.2.30 on 2026-08-04 23:23

from django.db import migrations, models


def zero_to_null(apps, schema_editor):
    """Existing kill_team_qa == 0 meant 'unset' (the old code could not distinguish an
    explicit $0 from the default, and always paid the $400 default for a 0). Convert those
    to NULL so pay is unchanged (NULL still → $400 default) while, going forward, a freshly
    entered $0 is stored as 0 and sticks."""
    WeeklyPayInput = apps.get_model('nomina', 'WeeklyPayInput')
    WeeklyPayInput.objects.filter(kill_team_qa=0).update(kill_team_qa=None)


def null_to_zero(apps, schema_editor):
    """Reverse: restore NULLs to 0 before the field goes non-nullable again."""
    WeeklyPayInput = apps.get_model('nomina', 'WeeklyPayInput')
    WeeklyPayInput.objects.filter(kill_team_qa__isnull=True).update(kill_team_qa=0)


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_payrollrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypayinput',
            name='kill_team_qa',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Kill Team QA bonus (MXN). NULL = never entered → the standard $400 default applies; an explicit value (including $0) is kept as-is.', max_digits=10, null=True),
        ),
        migrations.RunPython(zero_to_null, null_to_zero),
    ]
