# Generated by Django 4.2.30 on 2026-08-05 02:43

from django.db import migrations, models


def move_admin_extra_hours(apps, schema_editor):
    """Relocate admins' manual-hours correction from extra_hours into the new Admin Hours
    fields, so open-week admin pay is preserved on deploy. Before this change an official
    admin's manual hours lived in WeeklyPayInput.extra_hours; the Admin Nómina now reads
    hours_add − hours_deduct. Move any nonzero admin extra_hours across (positive → add,
    negative → deduct) and zero the old field. Regular agents are untouched — they keep
    using extra_hours on the Agent Nómina."""
    WeeklyPayInput = apps.get_model('nomina', 'WeeklyPayInput')
    Agent = apps.get_model('scheduling', 'Agent')
    admin_ids = set(Agent.objects.filter(is_official_admin=True).values_list('pk', flat=True))
    for wi in WeeklyPayInput.objects.exclude(extra_hours=0).filter(agent_id__in=admin_ids):
        net = wi.extra_hours
        wi.hours_add = net if net > 0 else 0
        wi.hours_deduct = -net if net < 0 else 0
        wi.extra_hours = 0
        wi.save(update_fields=['hours_add', 'hours_deduct', 'extra_hours'])


def restore_admin_extra_hours(apps, schema_editor):
    """Reverse: fold the Admin Hours net back into extra_hours before the fields drop."""
    WeeklyPayInput = apps.get_model('nomina', 'WeeklyPayInput')
    Agent = apps.get_model('scheduling', 'Agent')
    admin_ids = set(Agent.objects.filter(is_official_admin=True).values_list('pk', flat=True))
    for wi in WeeklyPayInput.objects.filter(agent_id__in=admin_ids):
        net = wi.hours_add - wi.hours_deduct
        if net:
            wi.extra_hours = net
            wi.save(update_fields=['extra_hours'])


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0012_alter_weeklypayinput_kill_team_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayinput',
            name='hours_add',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin Hours module: hours to ADD this week', max_digits=7),
        ),
        migrations.AddField(
            model_name='weeklypayinput',
            name='hours_deduct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin Hours module: hours to DEDUCT this week', max_digits=7),
        ),
        migrations.RunPython(move_admin_extra_hours, restore_admin_extra_hours),
    ]
