# Generated by Django 4.2.30 on 2026-05-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0008_agent_phone_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('P', 'P — Present'), ('T', 'T — Tardy'), ('Absent', 'Absent'), ('NCNS', 'NCNS — No Call No Show'), ('VTO', 'VTO — Voluntary Time Off'), ('IMSS', 'IMSS — Medical/IMSS Leave'), ('MUT', 'MUT — Make Up Time'), ('OT', 'OT — Over Time'), ('P+VTO', 'P+VTO — Present then VTO'), ('T+VTO', 'T+VTO — Tardy then VTO'), ('I', 'I — Incomplete Shift'), ('Quit', 'Quit'), ('Baja', 'Baja — Terminated'), ('V', 'V — Vacation')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to='scheduling.agent')),
            ],
            options={
                'ordering': ['date', 'agent'],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
