# Generated by Django 4.2.30 on 2026-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0002_adherencerecord_actual_hours_coding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencerecord',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
