# Generated by Django 4.2.30 on 2026-05-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_agent_phone_country_code'),
        ('adherence', '0003_alter_adherencerecord_actual_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('unmatched_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAgentHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five9_username', models.CharField(max_length=100)),
                ('agent_group', models.CharField(blank=True, max_length=100)),
                ('login_seconds', models.IntegerField(default=0)),
                ('not_ready_seconds', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_hours', to='scheduling.agent')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='adherence.dailyupload')),
            ],
            options={
                'ordering': ['five9_username'],
                'unique_together': {('upload', 'five9_username')},
            },
        ),
    ]
