# Generated by Django 4.2.30 on 2026-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0004_dailyupload_dailyagenthours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'P — Present'), ('T', 'T — Tardy'), ('Absent', 'Absent'), ('NCNS', 'NCNS — No Call No Show'), ('VTO', 'VTO — Voluntary Time Off'), ('IMSS', 'IMSS — Medical/IMSS Leave'), ('MUT', 'MUT — Make Up Time'), ('OT', 'OT — Over Time'), ('P+VTO', 'P+VTO — Present then VTO'), ('T+VTO', 'T+VTO — Tardy then VTO'), ('I', 'I — Incomplete Shift'), ('Quit', 'Quit'), ('Baja', 'Baja — Terminated'), ('V', 'V — Vacation'), ('LOA', 'LOA — Leave of Absence')], max_length=10),
        ),
    ]
