# Generated by Django 4.2.30 on 2026-05-29 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adherence', '0005_alter_adherencerecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_notes', to='scheduling.agent')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adherence_notes_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
