# Generated by Django 4.2.30 on 2026-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0007_add_ti_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adherencerecord',
            index=models.Index(fields=['date'], name='adherence_a_date_f4a98b_idx'),
        ),
        migrations.AddIndex(
            model_name='adherencerecord',
            index=models.Index(fields=['agent', 'date'], name='adherence_a_agent_i_778a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='coding',
            index=models.Index(fields=['agent', 'date'], name='adherence_c_agent_i_655f24_idx'),
        ),
        migrations.AddIndex(
            model_name='coding',
            index=models.Index(fields=['date'], name='adherence_c_date_ad9b4a_idx'),
        ),
    ]
