# Generated by Django 4.2.30 on 2026-06-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0009_coding_is_admin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyagenthours',
            index=models.Index(fields=['agent'], name='adherence_d_agent_i_a09fdb_idx'),
        ),
    ]
