# Generated by Django 4.2.30 on 2026-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0011_alter_adherencerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherencerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'P — Present'), ('T', 'T — Tardy'), ('Absent', 'Absent'), ('NCNS', 'NCNS — No Call No Show'), ('S', 'S — Suspension'), ('VTO', 'VTO — Voluntary Time Off'), ('IMSS', 'IMSS — Medical/IMSS Leave'), ('MUT', 'MUT — Make Up Time'), ('OT', 'OT — Over Time'), ('P+VTO', 'P+VTO — Present then VTO'), ('T+VTO', 'T+VTO — Tardy then VTO'), ('I', 'I — Incomplete Shift'), ('T+I', 'T+I — Tardy and Incomplete'), ('Quit', 'Quit'), ('Baja', 'Baja — Terminated'), ('V', 'V — Vacation'), ('LOA', 'LOA — Leave of Absence'), ('Holiday', 'Holiday — Company holiday (scheduled, not worked)'), ('Issues', 'Issues — Log-in/out issues (admin bonus penalty)')], max_length=10),
        ),
    ]
