# Generated by Django 4.2.30 on 2026-05-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErlangReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calls_per_hour', models.FloatField()),
                ('avg_handle_time', models.FloatField(help_text='Average handle time in seconds')),
                ('target_service_level', models.FloatField(help_text='Target service level as percentage (e.g. 80)')),
                ('target_answer_time', models.IntegerField(help_text='Target answer time in seconds (e.g. 20)')),
                ('agents_required', models.IntegerField(blank=True, null=True)),
                ('service_level_achieved', models.FloatField(blank=True, null=True)),
                ('occupancy', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
