# Generated by Django 4.2.30 on 2026-05-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erlang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erlangreport',
            name='agents_scheduled',
            field=models.IntegerField(blank=True, help_text='Agents needed after applying shrinkage', null=True),
        ),
        migrations.AddField(
            model_name='erlangreport',
            name='shrinkage',
            field=models.FloatField(default=0, help_text='Shrinkage percentage (e.g. 30 for 30%)'),
        ),
    ]
