# Generated by Django 4.2.30 on 2026-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erlang', '0002_erlangreport_agents_scheduled_erlangreport_shrinkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErlangActualStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('hour', models.IntegerField()),
                ('actual_agents', models.IntegerField()),
            ],
            options={
                'ordering': ['week_start', 'day', 'hour'],
                'unique_together': {('week_start', 'day', 'hour')},
            },
        ),
    ]
