# Generated by Django 4.2.30 on 2026-05-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erlang', '0003_erlangactualstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErlangCallRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('hour', models.IntegerField()),
                ('total_calls', models.FloatField()),
                ('avg_calls', models.FloatField()),
            ],
            options={
                'ordering': ['week_start', 'day', 'hour'],
                'unique_together': {('week_start', 'day', 'hour')},
            },
        ),
    ]
