# Generated by Django 4.2.30 on 2026-06-05 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erlang', '0005_erlangweekparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='erlangweekparams',
            name='calculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erlang_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erlangweekparams',
            name='csv_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erlangweekparams',
            name='csv_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erlang_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
