# Generated by Django 4.2.30 on 2026-06-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erlang', '0006_erlangweekparams_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='erlangreport',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
